### ISSUE TITLE
Pandas .astype('category') dramatically decreases performance

### ISSUE THREAD

**Issue by alexanderkuk** [bokeh/datashader#396] opened 2017-07-01 20:25 UTC
I have a DataFrame with 2 000 000 rows. It has columns client, driver, pickup_latitude, pickup_longitude. I do
```
table['client'] = table.client.astype('category')
table['driver'] = table.driver.astype('category')
```
to save some memory space. Aggregation
```
aggregate = canvas.points(table, 'pickup_longitude', 'pickup_latitude', ds.count())
```
runs for 4 seconds. 

If I do not cast client and driver to category, aggregation runs in 20ms. 

It is not obvious for me why .astype('category') decreases performance so much. It was hard to debug. Maybe add some notice or warning?

**Comment by jbednar** [comment] 2017-07-01 20:32
Is this a Pandas or a Dask dataframe?  Normally using categorical datatypes does not reduce performance, so this is definitely surprising, all the more so because the aggregation here is not using either of those columns. I'd need a reproducible example to try to figure it out.

**Comment by alexanderkuk** [comment] 2017-07-01 20:50
[data.csv.zip](https://github.com/bokeh/datashader/files/1117409/data.csv.zip)
```
table = pd.read_csv('data.csv.zip')
canvas = ds.Canvas(plot_width=700, plot_height=662, x_range=(4146921.8723705406, 4224887.706012843), y_range=(7470522.750106069, 7544365.4667577855))

%%timeit
aggregate = canvas.points(table, 'longitude', 'latitude', ds.count())
3.25 ms ± 350 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

table = pd.read_csv('data.csv.zip')
table['client'] = table.client.astype('category')
table['driver'] = table.driver.astype('category')

canvas = ds.Canvas(plot_width=700, plot_height=662, x_range=(4146921.8723705406, 4224887.706012843), y_range=(7470522.750106069, 7544365.4667577855))

%%timeit
aggregate = canvas.points(table, 'longitude', 'latitude', ds.count())
572 ms ± 24.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by jbednar** [comment] 2017-07-04 18:13
Thanks!  I've asked Greg to look into that when he gets the time.

**Comment by gbrener** [comment] 2017-08-01 19:58
I've taken a quick look at this, and it appears that in the categoricals case most of the time is spent doing schema validation with `odo`. Without categoricals, most of the time is spent in `Canvas.points()` (as expected). I suspect that there is a performance issue with the `odo` library in handling categorical dtypes.

**Comment by jbednar** [comment] 2017-08-01 20:37
Seems very suspicious!

**Comment by jcrist** [comment] 2017-08-01 20:44
I think we should just remove `odo` entirely. We initially used it to provide potential support for alternate data sources. Since we seem to have settled on `pandas`/`dask.dataframe` only, it doesn't make sense to have a generic dtype system as a dependency. I'd remove odo support and just use pandas dtypes directly.

**Comment by gbrener** [comment] 2017-08-02 18:39
@jcrist, just opened the PR to do this. The PR also address this performance issue, and brings categorical performance to be on-par with the case where they aren't used.

**Comment by gbrener** [comment] 2017-08-02 23:48
CC @teoliphant , as this partially relates to `datashape` performance, although most of the bottleneck appears to have gone away with the refactor in #561.

**Comment by jbednar** [comment] 2017-08-03 18:14
From discussions between me and Greg, it sounds like the underlying problems remaining after removing the `odo` code are that:

- datashape is encoding the type of every column in a dataframe, not just the ones datashader is using.  
- datashape's encoding for a categorical column includes a step where the full set of possible categorical values is turned into a tuple, which is expensive if there are a lot of categories

In our previous datashader work, the only categoricals we used were meant for datashader's ``count_cat`` aggregation, which is only meaningful for small numbers of category values (up to a few dozen), because (a) it results in one layer in the final aggregate array per category value (which would quickly blow up in memory if there are many possible values), and (b) these extra layers are used solely to construct a colorized final image, and there are only a few dozen colors that can be reliably distinguished categorically.  Thus we've never previously tested with categoricals larger than 100 categories, and had no problems with performance.

Here the problem is the very presence of categorical columns with large numbers of categories, even if we aren't actually using them in datashader -- datashape tries to encode those values as tuples, despite us never needing to use that information, and everything gets slow.  So, we could somehow maybe:

1. Specify which columns we want datashape to encode, i.e. only the three or so that datashader actually uses
2. Tell datashape to treat categoricals as integers, i.e. not worrying about the actual category values, just the presence of a categorical column
3. Optimize datashape to have a more efficient encoding for categorical values, e.g. using a numpy array rather than a tuple
4. Make a copy of the original dataframe, sharing the same underlying data, consisting of only the columns we need, and only call datashape on that

@gbrener, does that capture our full discussion?  Any idea which of these options we should move forward with?

**Comment by gbrener** [comment] 2017-08-03 18:24
Thanks for the summary @jbednar. I agree that it captures our discussion.

**Comment by gbrener** [comment] 2017-08-07 21:41
Revisiting this issue today, here are the timings for running `canvas.points()` 1000x, revealing the "new" bottleneck (pointing to the `datashape.Categoricals` constructor):

![screen shot 2017-08-07 at 4 07 52 pm](https://user-images.githubusercontent.com/2840348/29045854-ab9e65ac-7b8a-11e7-9880-53e15e2abe7b.png)

First I implemented option 4 from the list above, since it was relatively low-effort (I selected only the columns from the dataframe that were being used). Here were the results:

![screen shot 2017-08-07 at 4 11 40 pm](https://user-images.githubusercontent.com/2840348/29045990-27711d78-7b8b-11e7-8c81-b84c8cf271cd.png)


Notice that there's ~40% performance improvement for the dataframe with categoricals, but a ~25% performance decrease in the common case of a dataframe without categoricals. The time seemed to be spent in pandas dataframe selection internals. So I added a branch that says "if there is a categorical dtype in this dataframe, subset the columns. Otherwise use the whole dataframe". The relevant code is located [here](https://github.com/bokeh/datashader/blob/sidestep_categorical_cols/datashader/core.py#L371-L384):

![screen shot 2017-08-07 at 4 17 34 pm](https://user-images.githubusercontent.com/2840348/29046198-fd10cc80-7b8b-11e7-824a-b3680dd80b47.png)

This resulted in a ~38% improvement for the categoricals dataframe case, and ~10% perf decrease for the common case (overhead of checking for categoricals).

**Comment by gbrener** [comment] 2017-08-08 18:59
Sped things up a bit more in PR #431. There is now a ~50% increase in the categoricals case performance, with the non-categoricals performance staying roughly the same:

<img width="1123" alt="screen shot 2017-08-08 at 1 57 58 pm" src="https://user-images.githubusercontent.com/2840348/29089370-a6db400a-7c41-11e7-9f3d-a5dd45c05d4e.png">

**Comment by jbednar** [comment] 2017-08-08 19:58
Now that the PR is an overall clear improvement in performance, I've merged it.  @alexanderkuk, please try out the latest datashader master branch on your original problem, and if it doesn't address the performance issue, please open a new issue with your observations about the new levels of performance. Thanks for reporting this!

**Closed by jbednar** 2017-08-08 19:58 UTC

**Comment by alexanderkuk** [comment] 2017-08-10 16:34
Thank you! Before posting this issue I just removed .astype('category') from my code, so this is not a problem for me any more. Datashader was very useful in my work. By the way you can check out our project that uses Datashader http://lab.alexkuk.ru/taxi/

**Comment by jbednar** [comment] 2017-08-10 16:38
Very cool, thanks!
