### ISSUE TITLE
Multiple images in interactive images

### ISSUE THREAD

**Issue by hsparra** [bokeh/datashader#196] opened 2016-07-07 15:24 UTC
When zooming, it appears that the original image is kept and zoomed and the new image is placed on top so the individual points can be seen.

![nyc_taxi 2016-07-07 10-21-22](https://cloud.githubusercontent.com/assets/7515105/16658713/f763a376-442c-11e6-9691-86057ac5192b.png)

**Comment by hsparra** [comment] 2016-07-07 15:27
Also, initial load of image does not seem to match the viewport data range.

![image](https://cloud.githubusercontent.com/assets/7515105/16658812/5f73bb4a-442d-11e6-8f4d-9235d90d5d77.png)

**Comment by jbednar** [comment] 2016-07-07 18:12
That's odd; @philippjfr just tried this on his machine and had no problems, but he was on bokeh 0.12rc4, not the full 0.12 release.  He's trying that out now.   Meanwhile, I'm trying to debug it on my own system, with no luck yet.

**Comment by hsparra** [comment] 2016-07-07 18:45
@jbednar, just tried with a fresh environment and the zooming worked as expected. The old image was not kept. However, the initial load did not use the full viewport, as in the second image. Are the initial bounds in the notebook just larger than the area of the data?

**Comment by jbednar** [comment] 2016-07-07 18:56
Do you have any way to diff your two environments, to see what package versions might be at fault?  The initial bounds in the notebook are meant to match the data bounds precisely, at least when not overlaying geographic tiles, so there still seems to be a problem in your case.

**Comment by jbednar** [comment] 2016-07-07 19:34
I've tried setting up a new Python 3.4 environment using:

```
conda env create docs/environment.yml 
conda install jupyter
```

In general, it works well -- I couldn't reproduce the problem with the initial bounds mismatch between data and viewport, and it *mostly* works well when zooming.  But after enough mousing around I got:

![image](https://cloud.githubusercontent.com/assets/1695496/16666957/89dfbf10-444f-11e6-9c17-a3e982ead3e1.png)

Once this second image has appeared, it persists across zooms:

![image](https://cloud.githubusercontent.com/assets/1695496/16666980/a028f4ee-444f-11e6-8643-b210785066ee.png)

So there is definitely a problem here.  I'm using bokeh 0.12.0 and datashader master (0.3.0-8-g659d6dc)

**Comment by jbednar** [comment] 2016-07-07 19:36
The larger pixels in the background here are never updated; only the smaller ones in front redraw on a zoom or pan.

**Comment by jbednar** [comment] 2016-07-07 19:38
Other InteractiveImage cells in the same notebook continue to work fine; it's just this one cell I've managed to confuse.

**Comment by philippjfr** [comment] 2016-07-07 19:54
Very odd issue, because there should only ever be one image glyph created. Is there any output in the browser console? I'll try to reproduce it myself in a bit.

**Comment by jbednar** [comment] 2016-07-07 19:57
Nothing I can make sense of, and I'm not sure if it appeared before or after the plot involved:

![image](https://cloud.githubusercontent.com/assets/1695496/16667596/f4b2e01c-4452-11e6-8dd6-f8a91867541d.png)

I haven't been able to deliberately make another cell do the same thing, so I don't have any hints for how to reproduce it.  Seems like it must be a Bokeh issue if datashader creates only a single glyph.

**Comment by jbednar** [comment] 2016-07-07 20:00
The traceback shows:
```
<ipython-input-18-b6a38052e4e1> in <module>↵----> 1 from datashader.bokeh_ext import InteractiveImage; InteractiveImage._callbacks['492ad0bf-64da-4645-afd5-5ab4647d669e'].update({"xmin":-8242000,"ymin":null,"xmax":-8210000,"ymax":null,"w":750,"h":625})
```

**Comment by philippjfr** [comment] 2016-07-07 21:46
No idea why ``y_range.attributes.end`` would ever be null. For now I can handle that condition but we should investigate why the a Range1D object ends up with null values.

**Comment by jbednar** [comment] 2016-07-08 18:24
Looks like it's because the last two cells in the notebook were interacting.  Fixed in commit 8f84eaf.

**Closed by jbednar** 2016-07-08 18:24 UTC

**Comment by jbednar** [comment] 2016-07-08 18:25
@hsparra, pulling from master should fix the multiple-image problem.  Can you report whether you are still having the initial viewport problem?

**Comment by jbednar** [comment] 2016-07-08 20:29
We just checked, and it looks like his copy of the taxi data has fewer points, so we'll assume it was just using a restricted range.  Case solved, hopefully!
