### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by ea42gh** [bokeh/datashader#567] opened 2018-03-04 01:55 UTC
using pip to install datashader missed installing cloudpickle

**Comment by philippjfr** [comment] 2018-03-04 01:57
At the dask level ``cloudpickle`` seems to be in ``extra_require`` i.e. not a core dependency but for datashader it seems to be required so it might be worth adding it to the dependencies in setup.py.

**Comment by ceball** [comment] 2018-03-12 10:22
Duplicate of #549

**Closed by ceball** 2018-03-12 10:22 UTC
Labels: duplicate
